version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dayflow_db
    environment:
      POSTGRES_DB: hrms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: dayflow_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/hrms
      - SECRET_KEY=dayflow-hrms-super-secret-jwt-key-for-dev-environment-only-replace-in-prod
    depends_on:
      - db

volumes:
  postgres_data:
